const Map<String, String> translationsEnUs = {
  'New Chat': 'New Chat',
  'All Chat': 'All Chat',
  'Archived Chat': 'Archived Chat',
  'Profile': 'Profile',
  'Logout': 'Logout',
  'Chad Ai - Version 1.0.0': 'Chad Ai - Version 1.0.0',
  'Powered by Gemini': 'Powered by Gemini',
  'Terms of Use': 'Terms of Use',
  'Privacy Policy': 'Privacy Policy',
  'Chat Details': 'Chat Details',
  'Un-Archived chat is temporary that could lead to lost of history when changing devices. \n\nConsider Archiving your chat if you plan to save it on our Database':
      'Un-Archived chat is temporary that could lead to lost of history when changing devices. \n\nConsider Archiving your chat if you plan to save it on our Database',
  'Ask Me Anything...': 'Ask Me Anything...',
  'Chat Settings': 'Chat Settings',
  'Delete Chat': 'Delete Chat',
  'Archive Chat': 'Archive Chat',
  'Add New Chat': 'Add New Chat',
  'Chat Archived': 'Chat Archived',
  'Chat Succesfully Archived': 'Chat Succesfully Archived',
  'Chat Deleted': 'Chat Deleted',
  'Chat Succesfully Deleted': 'Chat Succesfully Deleted',
  'Currently you can only see your chat history, stay tunes for further updates':
      'Currently you can only see your chat history, stay tunes for further updates',
  'Profile & Settings': 'Profile & Settings',
  'Email': 'Email',
  'Theme': 'Theme',
  'System default': 'System default',
  'Language': 'Language',
  'Change Pin': 'Change Pin',
  'Change Password': 'Change Password',
  'Send Feedback': 'Send Feedback',
  'Chatbot AI can make mistakes. Consider checking important information and send us your feedback.':
      'Chatbot AI can make mistakes. Consider checking important information and send us your feedback.',
  'Current Pin': 'Current Pin',
  'New Pin': 'New Pin',
  'Retype New Pin': 'Retype New Pin',
  'Cancel': 'Cancel',
  'Send': 'Send',
  'Current Password': 'Current Password',
  'New Password': 'New Password',
  'Retype New Password': 'Retype New Password',
  'Feedback': 'Feedback',
  'Enter your feedback here...': 'Enter your feedback here...',
};
