const Map<String, String> translationsIdId = {
  'New Chat': 'Obrolan Baru',
  'All Chat': 'Semua Obrolan',
  'Archived Chat': 'Arsip Obrolan',
  'Archived Chat Details': 'Detail Obrolan',
  'Profile': 'Profil',
  'Logout': 'Keluar',
  'Chad Ai - Version 1.0.0': 'Chad Ai - Versi 1.0.0',
  'Powered by Gemini': 'Didukung oleh Gemini',
  'Terms of Use': 'Ketentuan',
  'Privacy Policy': 'Privasi',
  'Chat Details': 'Detail Obrolan',
  'Un-Archived chat is temporary that could lead to lost of history when changing devices. \n\nConsider Archiving your chat if you plan to save it on our Database':
      'Obrolan yang tidak diarsipkan bersifat sementara dan dapat menyebabkan kehilangan riwayat saat mengganti perangkat. \n\nPertimbangkan untuk mengarsipkan obrolan Anda jika Anda ingin menyimpannya di Basis Data kami.',
  'Ask Me Anything...': 'Tanyakan Apa Saja...',
  'Chat Settings': 'Pengaturan Obrolan',
  'Delete Chat': 'Hapus Obrolan',
  'Archive Chat': 'Arsipkan Obrolan',
  'Add New Chat': 'Tambahkan Obrolan Baru',
  'Chat Archived': 'Obrolan Diarsipkan',
  'Chat Succesfully Archived': 'Obrolan Berhasil Diarsipkan',
  'Chat Deleted': 'Obrolan Dihapus',
  'Chat Succesfully Deleted': 'Obrolan Berhasil Dihapus',
  'Currently you can only see your chat history, stay tunes for further updates':
      'Saat ini Anda hanya dapat melihat riwayat obrolan Anda, pantau terus untuk pembaruan selanjutnya',
  'Profile & Settings': 'Profil & Pengaturan',
  'Email': 'Email',
  'Theme': 'Tema',
  'System default': 'Bawaan sistem',
  'Language': 'Bahasa',
  'Change Pin': 'Ubah Pin',
  'Change Password': 'Ubah Kata Sandi',
  'Send Feedback': 'Kirim Masukan',
  'Chatbot AI can make mistakes. Consider checking important information and send us your feedback.':
      'Chatbot AI dapat membuat kesalahan. Pertimbangkan untuk memeriksa informasi penting dan kirimkan masukan Anda kepada kami.',
  'Current Pin': 'Pin Saat Ini',
  'New Pin': 'Pin Baru',
  'Retype New Pin': 'Ketik Ulang Pin Baru',
  'Cancel': 'Batal',
  'Send': 'Kirim',
  'Current Password': 'Kata Sandi Saat Ini',
  'New Password': 'Kata Sandi Baru',
  'Retype New Password': 'Ketik Ulang Kata Sandi Baru',
  'Feedback': 'Masukan',
  'Enter your feedback here...': 'Ketik masukan Anda di sini...',
};
